name: Generate Sitemap

on:
  push:
    branches: [ main ]
  schedule:
    - cron: '0 0 * * *'  # هر روز یکبار

jobs:
  generate-sitemap:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # اجازه push

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Generate Sitemap
        uses: cicirello/generate-sitemap@v1
        with:
          base-url: https://mohamadalikamalvand.github.io
          drop-html-extension: true

      - name: Commit & Push Sitemap
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Action"
          git add sitemap.xml
          
          if git diff --staged --quiet; then
            echo "No changes"
            exit 0
          fi
          
          git commit -m "Update sitemap.xml [skip ci]"
          git push origin HEAD:main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
