name: Generate Sitemap

on:
  push:
    branches: [ main ]
    paths:
      - '*.html'
      - 'assets/**'
  schedule:
    - cron: '0 0 * * *'

jobs:
  generate-sitemap:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # حذف setup-node و npm install

      - name: Generate Sitemap
        uses: cicirello/generate-sitemap@v1
        with:
          base-url: https://mohamadalikamalvand.github.io
          drop-html-extension: true

      - name: Commit & Push Changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.email "actions@github.com"
          git config user.name "GitHub Action"
          git add sitemap.xml
          
          if ! git diff --staged --quiet; then
            git commit -m "Update sitemap.xml [skip ci]"
            git push https://x-access-token:${GITHUB_TOKEN}@github.com/${{ github.repository }}.git HEAD:main
          else
            echo "No changes to sitemap.xml"
          fi
