name: Generate Sitemap

on:
  push:
    branches: [ main ]
    paths:
      - '*.html'
      - 'assets/**'
      - '!sitemap-new.xml'   # اینجا هم عوض کن
  schedule:
    - cron: '0 0 * * *'

jobs:
  generate-sitemap:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Generate Sitemap
        uses: cicirello/generate-sitemap@v1
        with:
          base-url: https://mohamadalikamalvand.github.io
          drop-html-extension: true
          path-to-sitemap: sitemap-new.xml   # نام جدید

      - name: Commit & Push Sitemap
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Action"
          git add sitemap-new.xml
          
          if git diff --staged --quiet; then
            echo "No changes in sitemap-new.xml"
            exit 0
          fi
          
          git commit -m "Update sitemap-new.xml [skip ci]"
          git push origin HEAD:main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
